[env:esp32-p4-evboard]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
board = esp32-p4-evboard
framework = arduino

lib_deps = 
    m5stack/M5Unified
    SD  ; ← これを明示的に追加
    FS

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1